name: Prod CD Workflow

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]

env:
  ECR_REPOSITORY_URI: clibmx-be-core
  CONTAINER_PORT: 8080

jobs:
  deploy-to-ec2:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.BE_CORE_EC2_HOST }}
          username: ${{ secrets.BE_CORE_EC2_USERNAME }}
          key: ${{ secrets.BE_CORE_EC2_SSH_KEY_PEM }}
          port: 22
          script: |
            # 1. AWS ECRì— ë¡œê·¸ì¸
            # EC2ì— ì—°ê²°ëœ IAM ì—­í•  ë•ë¶„ì— Access Key ì—†ì´ ë¡œê·¸ì¸ì´ ê°€ëŠ¥
            aws ecr get-login-password \
              --region ${{ secrets.AWS_REGION }} \
            | docker login \
              --username AWS \
              --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}
            
            # 2. ìµœì‹  Docker ì´ë¯¸ì§€ PULL
            docker pull ${{ secrets.ECR_REPOSITORY_URI }}:latest
            
            # 3. ê¸°ì¡´ì— ì‹¤í–‰ ì¤‘ì¸ ì»¨í…Œì´ë„ˆê°€ ìˆë‹¤ë©´ ì¤‘ì§€ ë° ì œê±°
            if [ $(docker ps -q --filter "name=${{ secrets.ECR_REPOSITORY_URI }}") ]; then
              echo "Stopping and removing existing container..."
              docker stop ${{ secrets.ECR_REPOSITORY_URI }}
              docker rm ${{ secrets.ECR_REPOSITORY_URI }}
              echo "Container stopped and removed."
            fi
            
            # 4. ìƒˆë¡œìš´ ì»¨í…Œì´ë„ˆ ì‹¤í–‰
            echo "Starting new container..."
            docker run -d -p ${{ env.CONTAINER_PORT }}:${{ env.CONTAINER_PORT }} \
              --name ${{ secrets.ECR_REPOSITORY_URI }} \
              --restart always \
              ${{ secrets.ECR_REPOSITORY_URI }}:latest
            
            echo "New container started successfully."

            # 5. ì‚¬ìš©ë˜ì§€ ì•ŠëŠ” ì˜¤ë˜ëœ Docker ì´ë¯¸ì§€ ì •ë¦¬ (ë””ìŠ¤í¬ ê³µê°„ í™•ë³´)
            docker image prune -af
            
            echo "ğŸš€ Deployment to EC2 completed successfully!"
